const SYMBOL_WIDTH = 20
const SYMBOL_HEIGHT = 50
const TEXT_WRAPPER_MARGIN = 100

const TEXT_WRAPPER_SIZE = window.innerWidth - TEXT_WRAPPER_MARGIN * 2

export { SYMBOL_WIDTH, SYMBOL_HEIGHT, TEXT_WRAPPER_MARGIN, TEXT_WRAPPER_SIZE }
