const SYMBOL_WIDTH = 20
const SYMBOL_HEIGHT = 50
const DEFAULT_FONT_SIZE = 32

const DEFAULT_CARET_WIDTH = 3
const DEFAULT_CARET_HEIGHT = 38

const UNDERLINE_CARET_WIDTH = SYMBOL_WIDTH
const UNDERLINE_CARET_HEIGHT = 3

const INSERT_CARET_WIDTH = SYMBOL_WIDTH
const INSERT_CARET_HEIGHT = SYMBOL_HEIGHT

const TEXT_WRAPPER_MARGIN = 100

export {
  SYMBOL_WIDTH,
  SYMBOL_HEIGHT,
  DEFAULT_FONT_SIZE,
  DEFAULT_CARET_WIDTH,
  DEFAULT_CARET_HEIGHT,
  UNDERLINE_CARET_WIDTH,
  UNDERLINE_CARET_HEIGHT,
  INSERT_CARET_WIDTH,
  INSERT_CARET_HEIGHT,
  TEXT_WRAPPER_MARGIN,
}
